name: auto update

on:
  push:
    branches:
      - main
  schedule:
    # At minute 10,40.
    - cron: '10,40 * * * *'

jobs:
  build:
    name: Auto-update master data
    env:
      MY_SECRET: ${{ secrets.commit_secret }}
      USER_NAME: githubaction
      USER_EMAIL: githubaction@fake.com
      PUBLISH_DIR: master-data
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Installation
        run: |
          yarn install

      - name: Download master data
        run: |
          # Get ja-JP master data
          yarn download:official-master-data
          # Translate to other locale
          yarn translate:gen-master-json
          yarn translate:gen-catalog-data
          # Export TSV
          yarn translate:gen-tsv ja-JP
          yarn translate:gen-tsv zh-TW

      - name: Diff with previous commit and commit files
        run: |
          mkdir artifacts
          # Add dummy entries to the index for the diff
          git add -N .
          git diff $PUBLISH_DIR/latest/ > artifacts/$PUBLISH_DIR.diff

          DIFF_SIZE=$(wc -c artifacts/$PUBLISH_DIR.diff | awk '{print $1}')
          APP_VERSION=$(cat $PUBLISH_DIR/AppVersion)
          MASTER_VERSION=$(cat $PUBLISH_DIR/MasterVersion)

          if [ "$DIFF_SIZE" -eq "0" ]; then
            echo "Master data is already up to date."
          else
            echo "Master data is updated."

            git config --local user.name $USER_NAME
            git config --local user.email $USER_EMAIL
            git status
            git add --all
            git commit -m "master data auto-update (app: $APP_VERSION ; master: $MASTER_VERSION)"
            git push origin HEAD
            echo "🤘 update version complete."
          fi

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ env.MY_SECRET }}
          event-type: auto-update
